#application config
app:
  name: soular

spring:
  profiles:
    active: prd

# Project access address
external:
  url: http://e.eas.tiklab.net

#web config
server:
  port: 8080

#jdbc config
jdbc:
  driverClassName: org.postgresql.Driver
  url: jdbc:postgresql://localhost:5432/eas_ce?stringtype=unspecified
  username: postgres
  password: darth2020

DATA_HOME: /opt/tiklab/darth-ee

#dcs config
dcs:
  server:
    enabled: true
    port: 5030
    datapath: ${DATA_HOME}/caches
  client:
    url: 127.0.0.1:5030
    group: g1
    database: dcs1
    expire: 7200

#postgresql config
postgresql:
  embbed:
    enable: true
  database: eas_ce
  db:
    port: 5432
    username: postgres
    password: darth2020
    address: ${DATA_HOME}\postgresql
