app:
  name: thoughtware-eas
  
spring:
  config:
    import: optional:classpath:/config/${env:local}/application.yaml
  profiles:
    active: release

base:
  url: http://localhost:8080

server:
  port: 8080


jdbc:
  driverClassName: org.postgresql.Driver
  url: jdbc:postgresql://localhost:6000/eas_ce?stringtype=unspecified
  username: postgres
  password: darth2020

DATA_HOME: C:\thoughtware\eas

#dfs config
dfs:
  server:
    #    enabled: true
    #    mode:server
    port: 4001
    datapath: ${DATA_HOME}/files
  client:
    url: 172.10.1.11:4001
    bucket: ${app.name}

#dfs
file:
  path: http://file.thoughtware.net

#dcs config
dcs:
  server:
    enabled: true
    port: 5030
    datapath: ${DATA_HOME}/caches
  client:
    url: 127.0.0.1:5030
    group: g1
    database: dcs1
    expire: 7200

#dss config

dss:
  server:
    #    enabled: true
    #    mode:server
    port: 6001
    datapath: ${DATA_HOME}/index
  client:
    url: 172.10.1.11:6001
    bucket: ${app.name}

#integration config
homes:
  address: https://thoughtware.cn

postgresql:
  embbed:
    enable: true
  database: eas_ce
  db:
    port: 6000
    username: postgres
    password: darth2020
    address: ${DATA_HOME}/postgresql

#plugin config
plugin:
  path: ${DATA_HOME}/plugin

#tenant config
tenant:
  application: eas-ce

eas:
  embbed:
    enable: true

backups:
  time: 0 0 2 * * ?
  dir: /data/eas-ce

#licences config
licences:
  path: ${DATA_HOME}/licences

auth:
  wechat_suite_id: null
  wechat_secret: null
  wechat_token: null
  wechat_encodingAESKey: null
