     #application config
app:
  name: soular

server:
  port: 8080

external:
  url: http://192.168.10.35:3010

jdbc:
  driverClassName: org.postgresql.Driver
  url: jdbc:postgresql://172.10.1.10:5432/tiklab_eas?stringtype=unspecified
  username: postgres
  password: darth2020

DATA_HOME: ${user.home}/tiklab/tiklab-soular

#dcs
dcs:
  server:
    enabled: true
    port: 5035
    datapath: ${DATA_HOME}/caches
  client:
    url: 127.0.0.1:5035
    group: g1
    database: dcs1
    expire: 7200
  app:
    url: 127.0.0.1:5035
    group: g1
    database: app
    expire: 604800


postgresql:
  type: local
