#application config
app:
  name: tiklab-eas

spring:
  config:
    import: optional:classpath:/config/${env:dev}/application.yaml

# Project access address
base:
  url: http://192.168.10.14:3001

#web config
server:
  port: 8080
# enable eas to project

#dal config

#dal config for mysql jdbc
#jdbc:
#  driverClassName: com.mysql.cj.jdbc.Driver
#  url: jdbc:mysql://localhost:3306/tiklab_eas?characterEncoding=utf8&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
#  username: root
#  password: darth2020
jdbc:
  driverClassName: org.postgresql.Driver
  url: jdbc:postgresql://172.12.1.16:5432/tiklab_eas?stringtype=unspecified
  username: postgres
  password: darth2020

mysql:
  database: tiklab_eas
  embbed:
    enable: true


PROJECT_HOME: ${user.home}/tiklab/${app.name}
DATA_HOME: ${user.home}/tiklab/${app.name}

#dfs config
#dfs.server.enabled=false
#dfs.server.mode=server
dfs:
  server:
    #    enabled: true
    #    mode:server
    port: 4001
    datapath: ${DATA_HOME}/files
  client:
    url: 172.10.1.11:4001
    bucket: ${app.name}



#dfs
file:
  path: http://file.tiklab.net
#dcs config
#dcs.server.enabled=false
#dcs.server.mode=server
dcs:
  server:
    #    enabled: true
    #    mode:server
    port: 5001
    datapath: ${DATA_HOME}/caches
  client:
    url: 172.10.1.11:5001
    bucket: ${app.name}
#dss config
#dss.server.enabled=false
#dss.server.mode=server
dss:
  server:
    #    enabled: true
    #    mode:server
    port: 6001
    datapath: ${DATA_HOME}/index
  client:
    url: 172.10.1.11:6001
    bucket: ${app.name}



#integration config
homes:
  address: http://139.196.76.221:8081
#plugin config
plugin:
  path: ${DATA_HOME}/plugin

#tenant config
tenant:
  application: eas

eas:
  embbed:
    enable: true

#licences config
licences:
  path: ${DATA_HOME}/licences

auth:
  wechat_suite_id: null
  wechat_secret: null
  wechat_token: null
  wechat_encodingAESKey: null
