#application config
app:
  name: tiklab-eas

spring:
  profiles:
    active: dev

#web config
server:
  port: 8082

base:
  url: http://eas-ce.dev.tiklab.net

jdbc:
  driverClassName: org.postgresql.Driver
  url: jdbc:postgresql://172.10.1.10:5432/tiklab_eas?stringtype=unspecified
  username: postgres
  password: darth2020

DATA_HOME: /opt/tiklab/eas

#dfs config
#dfs config
dfs:
  server:
    port: 4000
    datapath: ${DATA_HOME}/files
  client:
    url: 172.10.1.11:4000
    bucket: ${app.name}

#dcs config
dcs:
  server:
    enabled: true
    port: 5030
    datapath: ${DATA_HOME}/caches
  client:
    url: 127.0.0.1:5030
    group: g1
    database: dcs1
    expire: 7200


#dfs
file:
  path: http://file.dev.tiklab.net

#dss config
#dss.server.enabled=false
#dss.server.mode=server
dss:
  server:
    #    enabled: true
    #    mode:server
    port: 6000
    datapath: ${DATA_HOME}/index
  client:
    url: 172.10.1.11:6000
    bucket: ${app.name}


#auth config
#auth.type=acc
#auth.address=http://www.tiklab.cn

#integration config
homes:
  address: http://homes-api.tiklab.net

#plugin config
plugin:
  path: ${DATA_HOME}/plugin

#tenant config
tenant:
  application: eas

eas:
  embbed:
    enable: true

#licences config
licences:
  path: ${DATA_HOME}/licences

auth:
  type: local
  wechat_suite_id: null
  wechat_secret: null
  wechat_token: null
  wechat_encodingAESKey: null
