app:
  name: soular
  
spring:
  config:
    import: optional:classpath:/config/${env:local}/application.yaml
  profiles:
    active: release

external:
  url: http://localhost:8080

server:
  port: 8080

jdbc:
  driverClassName: org.postgresql.Driver
  url: jdbc:postgresql://localhost:6000/tiklab_soular?stringtype=unspecified
  username: postgres
  password: darth2020

DATA_HOME: /opt/tiklab/eas

#dcs config
dcs:
  server:
    enabled: true
    port: 5030
    datapath: ${DATA_HOME}/caches
  client:
    url: 127.0.0.1:5030
    group: g1
    database: dcs1
    expire: 7200

postgresql:
  embbed:
    enable: true
  database: tiklab_soular
  db:
    port: 6000
    username: postgres
    password: darth2020
    address: ${DATA_HOME}/postgresql
