#application config
app:
  name: tiklab-eas

# Project access address
base:
  url: http://bac.eas.demo.tiklab.net

#web config
server:
  port: 8080
# enable eas to project

jdbc:
  driverClassName: org.postgresql.Driver
  url: jdbc:postgresql://172.12.1.10:5432/tiklab_eas?stringtype=unspecified
  username: postgres
  password: darth2020

PROJECT_HOME: ${user.home}/tiklab/${app.name}
DATA_HOME: ${user.home}/tiklab/${app.name}

#dfs config
#dfs.server.enabled=false
#dfs.server.mode=server
dfs:
  server:
    #    enabled: true
    #    mode:server
    port: 4001
    datapath: ${DATA_HOME}/files
  client:
    url: 172.10.1.11:4001
    bucket: ${app.name}



#dfs
file:
  path: http://file.tiklab.net
#dcs config
#dcs.server.enabled=false
#dcs.server.mode=server
dcs:
  server:
    #    enabled: true
    #    mode:server
    port: 5001
    datapath: ${DATA_HOME}/caches
  client:
    url: 172.10.1.11:5001
    bucket: ${app.name}
#dss config
#dss.server.enabled=false
#dss.server.mode=server
dss:
  server:
    #    enabled: true
    #    mode:server
    port: 6001
    datapath: ${DATA_HOME}/index
  client:
    url: 172.10.1.11:6001
    bucket: ${app.name}



#integration config
homes:
  address:  http://homes.demo.tiklab.net

#plugin config
plugin:
  path: ${DATA_HOME}/plugin

#tenant config
tenant:
  application: eas

eas:
  embbed:
    enable: true

#licences config
licences:
  path: ${DATA_HOME}/licences

auth:
  wechat_suite_id: null
  wechat_secret: null
  wechat_token: null
  wechat_encodingAESKey: null
