#application config
app:
  name: tiklab-eas

spring:
  config:
    import: optional:classpath:/config/${env:local}/application.yaml

# Project access address
base:
  url: http://eas-ce.prd.tiklab.net

#web config
server:
  port: 8080

#dal config

jdbc:
  driverClassName: org.postgresql.Driver
  url: jdbc:postgresql://172.13.1.13:5432/tiklab_eas?stringtype=unspecified
  username: postgres
  password: darth2020

DATA_HOME: /opt/tiklab/${app.name}

#dfs config
dfs:
  server:
    #    enabled: true
    #    mode:server
    port: 4001
    datapath: ${DATA_HOME}/files
  client:
    url: 172.10.1.11:4001
    bucket: ${app.name}



#dfs
file:
  path: http://file.tiklab.net
#dcs config

dcs:
  server:
    enabled: true
    port: 5030
    datapath: ${DATA_HOME}/caches
  client:
    url: 127.0.0.1:5030
    group: g1
    database: dcs1
    expire: 7200
    
#dss config

dss:
  server:
    #    enabled: true
    #    mode:server
    port: 6001
    datapath: ${DATA_HOME}/index
  client:
    url: 172.10.1.11:6001
    bucket: ${app.name}



#integration config
homes:
  address: http://139.196.76.221:8081
#plugin config
plugin:
  path: ${DATA_HOME}/plugin

#tenant config
tenant:
  application: eas

eas:
  embbed:
    enable: true

#licences config
licences:
  path: ${DATA_HOME}/licences

auth:
  wechat_suite_id: null
  wechat_secret: null
  wechat_token: null
  wechat_encodingAESKey: null
