#application config
app:
  name: eas

spring:
  profiles:
    active: dev

#web config
server:
  port: 8080


base:
  url: http://eas-ce.dev.tiklab.net

jdbc:
  driverClassName: org.postgresql.Driver
  url: jdbc:postgresql://172.10.1.10:5432/tiklab_eas?stringtype=unspecified
  username: postgres
  password: darth2020



PROJECT_HOME: ${user.home}/tiklab/${app.name}
DATA_HOME: ${user.home}/tiklab/${app.name}


#dfs config
#dfs.server.enabled=false
#dfs.server.mode=server
dfs:
  server:
#    enabled: true
#    mode:server
    port: 4000
    datapath: ${DATA_HOME}/files
  client:
    url: 172.10.1.11:4000
    bucket: ${app.name}


#dfs
file:
  path: http://file.dev.tiklab.net

#dcs config
#dcs.server.enabled=false
#dcs.server.mode=server
dcs:
  server:
    #    enabled: true
    #    mode:server
    port: 5000
    datapath: ${DATA_HOME}/caches
  client:
    url: 172.10.1.11:5000
    bucket: ${app.name}


#dss config
#dss.server.enabled=false
#dss.server.mode=server
dss:
  server:
    #    enabled: true
    #    mode:server
    port: 6000
    datapath: ${DATA_HOME}/index
  client:
    url: 172.10.1.11:6000
    bucket: ${app.name}


#auth config
#auth.type=acc
#auth.address=http://www.tiklab.cn

#integration config
homes:
  address: http://192.168.10.7:8080

#plugin config
plugin:
  path: ${PROJECT_HOME}/plugin

#tenant config
tenant:
  application: eas

eas:
  embbed:
    enable: true

#licences config
licences:
  path: ${DATA_HOME}/licences

auth:
  type: local
  wechat_suite_id: null
  wechat_secret: null
  wechat_token: null
  wechat_encodingAESKey: null
